-- 900개 영어 단어 추가 (난이도: easy 250개, medium 400개, hard 250개)
-- 카테고리: Education, Career, Emotions, Health, Sports, Technology, Nature, Travel, Hobbies, Music, Art, Science, History, Politics, Economy

-- Education (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('student', '학생', 'Education', 'easy'),
('teacher', '선생님', 'Education', 'easy'),
('school', '학교', 'Education', 'easy'),
('book', '책', 'Education', 'easy'),
('pencil', '연필', 'Education', 'easy'),
('desk', '책상', 'Education', 'easy'),
('classroom', '교실', 'Education', 'easy'),
('homework', '숙제', 'Education', 'easy'),
('test', '시험', 'Education', 'easy'),
('grade', '성적', 'Education', 'easy'),
('lesson', '수업', 'Education', 'easy'),
('study', '공부하다', 'Education', 'easy'),
('learn', '배우다', 'Education', 'easy'),
('read', '읽다', 'Education', 'easy'),
('write', '쓰다', 'Education', 'easy'),
('library', '도서관', 'Education', 'easy'),
('notebook', '공책', 'Education', 'easy'),
('eraser', '지우개', 'Education', 'easy'),
('ruler', '자', 'Education', 'easy'),
('backpack', '가방', 'Education', 'easy'),

('university', '대학교', 'Education', 'medium'),
('professor', '교수', 'Education', 'medium'),
('lecture', '강의', 'Education', 'medium'),
('semester', '학기', 'Education', 'medium'),
('curriculum', '교육과정', 'Education', 'medium'),
('assignment', '과제', 'Education', 'medium'),
('research', '연구', 'Education', 'medium'),
('scholarship', '장학금', 'Education', 'medium'),
('diploma', '졸업장', 'Education', 'medium'),
('tuition', '등록금', 'Education', 'medium'),
('campus', '캠퍼스', 'Education', 'medium'),
('major', '전공', 'Education', 'medium'),
('minor', '부전공', 'Education', 'medium'),
('degree', '학위', 'Education', 'medium'),
('graduate', '졸업하다', 'Education', 'medium'),
('enroll', '등록하다', 'Education', 'medium'),
('attendance', '출석', 'Education', 'medium'),
('syllabus', '강의계획서', 'Education', 'medium'),
('textbook', '교과서', 'Education', 'medium'),
('laboratory', '실험실', 'Education', 'medium'),
('examination', '시험', 'Education', 'medium'),
('certificate', '증명서', 'Education', 'medium'),
('academic', '학문의', 'Education', 'medium'),
('discipline', '학문분야', 'Education', 'medium'),
('comprehension', '이해', 'Education', 'medium'),

('pedagogy', '교육학', 'Education', 'hard'),
('dissertation', '논문', 'Education', 'hard'),
('accreditation', '인증', 'Education', 'hard'),
('matriculation', '입학', 'Education', 'hard'),
('curriculum vitae', '이력서', 'Education', 'hard'),
('epistemology', '인식론', 'Education', 'hard'),
('heuristic', '발견적', 'Education', 'hard'),
('empirical', '경험적인', 'Education', 'hard'),
('methodology', '방법론', 'Education', 'hard'),
('theoretical', '이론적인', 'Education', 'hard'),
('hypothesis', '가설', 'Education', 'hard'),
('plagiarism', '표절', 'Education', 'hard'),
('symposium', '심포지엄', 'Education', 'hard'),
('tenure', '종신재직권', 'Education', 'hard'),
('prerequisite', '선수과목', 'Education', 'hard');

-- Career (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('job', '직업', 'Career', 'easy'),
('work', '일', 'Career', 'easy'),
('office', '사무실', 'Career', 'easy'),
('boss', '상사', 'Career', 'easy'),
('employee', '직원', 'Career', 'easy'),
('salary', '급여', 'Career', 'easy'),
('meeting', '회의', 'Career', 'easy'),
('project', '프로젝트', 'Career', 'easy'),
('team', '팀', 'Career', 'easy'),
('manager', '관리자', 'Career', 'easy'),
('company', '회사', 'Career', 'easy'),
('business', '사업', 'Career', 'easy'),
('customer', '고객', 'Career', 'easy'),
('service', '서비스', 'Career', 'easy'),
('product', '제품', 'Career', 'easy'),
('schedule', '일정', 'Career', 'easy'),
('deadline', '마감일', 'Career', 'easy'),
('email', '이메일', 'Career', 'easy'),
('report', '보고서', 'Career', 'easy'),
('presentation', '발표', 'Career', 'easy'),

('entrepreneur', '기업가', 'Career', 'medium'),
('corporation', '기업', 'Career', 'medium'),
('department', '부서', 'Career', 'medium'),
('colleague', '동료', 'Career', 'medium'),
('promotion', '승진', 'Career', 'medium'),
('contract', '계약', 'Career', 'medium'),
('negotiation', '협상', 'Career', 'medium'),
('strategy', '전략', 'Career', 'medium'),
('revenue', '수익', 'Career', 'medium'),
('profit', '이익', 'Career', 'medium'),
('investment', '투자', 'Career', 'medium'),
('marketing', '마케팅', 'Career', 'medium'),
('advertising', '광고', 'Career', 'medium'),
('budget', '예산', 'Career', 'medium'),
('expense', '비용', 'Career', 'medium'),
('productivity', '생산성', 'Career', 'medium'),
('efficiency', '효율성', 'Career', 'medium'),
('performance', '성과', 'Career', 'medium'),
('evaluation', '평가', 'Career', 'medium'),
('compensation', '보상', 'Career', 'medium'),
('benefits', '복리후생', 'Career', 'medium'),
('recruitment', '채용', 'Career', 'medium'),
('resignation', '사직', 'Career', 'medium'),
('retirement', '은퇴', 'Career', 'medium'),
('freelance', '프리랜서', 'Career', 'medium'),

('entrepreneurship', '기업가정신', 'Career', 'hard'),
('stakeholder', '이해관계자', 'Career', 'hard'),
('merger', '합병', 'Career', 'hard'),
('acquisition', '인수', 'Career', 'hard'),
('subsidiary', '자회사', 'Career', 'hard'),
('diversification', '다각화', 'Career', 'hard'),
('synergy', '시너지', 'Career', 'hard'),
('leverage', '레버리지', 'Career', 'hard'),
('arbitration', '중재', 'Career', 'hard'),
('compliance', '준수', 'Career', 'hard'),
('liability', '책임', 'Career', 'hard'),
('intellectual property', '지적재산', 'Career', 'hard'),
('confidentiality', '기밀성', 'Career', 'hard'),
('non-disclosure', '비공개', 'Career', 'hard'),
('severance', '퇴직금', 'Career', 'hard');

-- Emotions (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('happy', '행복한', 'Emotions', 'easy'),
('sad', '슬픈', 'Emotions', 'easy'),
('angry', '화난', 'Emotions', 'easy'),
('scared', '무서운', 'Emotions', 'easy'),
('excited', '신난', 'Emotions', 'easy'),
('tired', '피곤한', 'Emotions', 'easy'),
('bored', '지루한', 'Emotions', 'easy'),
('surprised', '놀란', 'Emotions', 'easy'),
('worried', '걱정되는', 'Emotions', 'easy'),
('nervous', '긴장한', 'Emotions', 'easy'),
('proud', '자랑스러운', 'Emotions', 'easy'),
('shy', '수줍은', 'Emotions', 'easy'),
('lonely', '외로운', 'Emotions', 'easy'),
('confused', '혼란스러운', 'Emotions', 'easy'),
('calm', '차분한', 'Emotions', 'easy'),
('relaxed', '편안한', 'Emotions', 'easy'),
('cheerful', '명랑한', 'Emotions', 'easy'),
('grateful', '감사한', 'Emotions', 'easy'),
('jealous', '질투하는', 'Emotions', 'easy'),
('disappointed', '실망한', 'Emotions', 'easy'),

('anxious', '불안한', 'Emotions', 'medium'),
('frustrated', '좌절한', 'Emotions', 'medium'),
('overwhelmed', '압도된', 'Emotions', 'medium'),
('enthusiastic', '열정적인', 'Emotions', 'medium'),
('optimistic', '낙관적인', 'Emotions', 'medium'),
('pessimistic', '비관적인', 'Emotions', 'medium'),
('nostalgic', '향수에 젖은', 'Emotions', 'medium'),
('embarrassed', '당황한', 'Emotions', 'medium'),
('ashamed', '부끄러운', 'Emotions', 'medium'),
('guilty', '죄책감 드는', 'Emotions', 'medium'),
('resentful', '분개한', 'Emotions', 'medium'),
('indifferent', '무관심한', 'Emotions', 'medium'),
('sympathetic', '동정적인', 'Emotions', 'medium'),
('empathetic', '공감하는', 'Emotions', 'medium'),
('compassionate', '자비로운', 'Emotions', 'medium'),
('content', '만족한', 'Emotions', 'medium'),
('ecstatic', '황홀한', 'Emotions', 'medium'),
('melancholy', '우울한', 'Emotions', 'medium'),
('irritated', '짜증난', 'Emotions', 'medium'),
('agitated', '동요된', 'Emotions', 'medium'),
('serene', '평온한', 'Emotions', 'medium'),
('delighted', '기쁜', 'Emotions', 'medium'),
('dismayed', '낙담한', 'Emotions', 'medium'),
('apprehensive', '걱정하는', 'Emotions', 'medium'),
('exhilarated', '들뜬', 'Emotions', 'medium'),

('euphoric', '도취된', 'Emotions', 'hard'),
('despondent', '낙담한', 'Emotions', 'hard'),
('indignant', '분개한', 'Emotions', 'hard'),
('ambivalent', '양가감정의', 'Emotions', 'hard'),
('complacent', '자기만족의', 'Emotions', 'hard'),
('contemptuous', '경멸하는', 'Emotions', 'hard'),
('vindictive', '복수심 강한', 'Emotions', 'hard'),
('remorseful', '후회하는', 'Emotions', 'hard'),
('wistful', '그리워하는', 'Emotions', 'hard'),
('jubilant', '환희에 찬', 'Emotions', 'hard'),
('morose', '시무룩한', 'Emotions', 'hard'),
('petulant', '성마른', 'Emotions', 'hard'),
('sanguine', '낙천적인', 'Emotions', 'hard'),
('stoic', '금욕적인', 'Emotions', 'hard'),
('vexed', '괴로워하는', 'Emotions', 'hard');

-- Health (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('doctor', '의사', 'Health', 'easy'),
('nurse', '간호사', 'Health', 'easy'),
('hospital', '병원', 'Health', 'easy'),
('medicine', '약', 'Health', 'easy'),
('sick', '아픈', 'Health', 'easy'),
('pain', '통증', 'Health', 'easy'),
('fever', '열', 'Health', 'easy'),
('cough', '기침', 'Health', 'easy'),
('cold', '감기', 'Health', 'easy'),
('headache', '두통', 'Health', 'easy'),
('healthy', '건강한', 'Health', 'easy'),
('exercise', '운동', 'Health', 'easy'),
('diet', '식단', 'Health', 'easy'),
('sleep', '수면', 'Health', 'easy'),
('vitamin', '비타민', 'Health', 'easy'),
('injury', '부상', 'Health', 'easy'),
('bandage', '붕대', 'Health', 'easy'),
('pill', '알약', 'Health', 'easy'),
('checkup', '검진', 'Health', 'easy'),
('treatment', '치료', 'Health', 'easy'),

('physician', '내과의사', 'Health', 'medium'),
('surgeon', '외과의사', 'Health', 'medium'),
('diagnosis', '진단', 'Health', 'medium'),
('symptom', '증상', 'Health', 'medium'),
('prescription', '처방전', 'Health', 'medium'),
('therapy', '치료법', 'Health', 'medium'),
('rehabilitation', '재활', 'Health', 'medium'),
('vaccination', '예방접종', 'Health', 'medium'),
('immunity', '면역', 'Health', 'medium'),
('infection', '감염', 'Health', 'medium'),
('inflammation', '염증', 'Health', 'medium'),
('chronic', '만성의', 'Health', 'medium'),
('acute', '급성의', 'Health', 'medium'),
('allergy', '알레르기', 'Health', 'medium'),
('diabetes', '당뇨병', 'Health', 'medium'),
('hypertension', '고혈압', 'Health', 'medium'),
('obesity', '비만', 'Health', 'medium'),
('nutrition', '영양', 'Health', 'medium'),
('metabolism', '신진대사', 'Health', 'medium'),
('cardiovascular', '심혈관의', 'Health', 'medium'),
('respiratory', '호흡기의', 'Health', 'medium'),
('digestive', '소화의', 'Health', 'medium'),
('neurological', '신경학적', 'Health', 'medium'),
('psychiatric', '정신과의', 'Health', 'medium'),
('preventive', '예방의', 'Health', 'medium'),

('epidemiology', '역학', 'Health', 'hard'),
('pathology', '병리학', 'Health', 'hard'),
('immunology', '면역학', 'Health', 'hard'),
('pharmacology', '약리학', 'Health', 'hard'),
('anesthesia', '마취', 'Health', 'hard'),
('prognosis', '예후', 'Health', 'hard'),
('malignant', '악성의', 'Health', 'hard'),
('benign', '양성의', 'Health', 'hard'),
('congenital', '선천적인', 'Health', 'hard'),
('hereditary', '유전적인', 'Health', 'hard'),
('palliative', '완화의', 'Health', 'hard'),
('remission', '완화', 'Health', 'hard'),
('metastasis', '전이', 'Health', 'hard'),
('comorbidity', '동반질환', 'Health', 'hard'),
('contraindication', '금기사항', 'Health', 'hard');

-- Sports (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('ball', '공', 'Sports', 'easy'),
('game', '경기', 'Sports', 'easy'),
('team', '팀', 'Sports', 'easy'),
('player', '선수', 'Sports', 'easy'),
('coach', '코치', 'Sports', 'easy'),
('win', '이기다', 'Sports', 'easy'),
('lose', '지다', 'Sports', 'easy'),
('score', '점수', 'Sports', 'easy'),
('goal', '골', 'Sports', 'easy'),
('run', '달리다', 'Sports', 'easy'),
('jump', '뛰다', 'Sports', 'easy'),
('swim', '수영하다', 'Sports', 'easy'),
('kick', '차다', 'Sports', 'easy'),
('throw', '던지다', 'Sports', 'easy'),
('catch', '잡다', 'Sports', 'easy'),
('race', '경주', 'Sports', 'easy'),
('match', '경기', 'Sports', 'easy'),
('practice', '연습', 'Sports', 'easy'),
('champion', '챔피언', 'Sports', 'easy'),
('medal', '메달', 'Sports', 'easy'),

('tournament', '토너먼트', 'Sports', 'medium'),
('championship', '선수권대회', 'Sports', 'medium'),
('athlete', '운동선수', 'Sports', 'medium'),
('competition', '대회', 'Sports', 'medium'),
('opponent', '상대', 'Sports', 'medium'),
('referee', '심판', 'Sports', 'medium'),
('spectator', '관중', 'Sports', 'medium'),
('stadium', '경기장', 'Sports', 'medium'),
('training', '훈련', 'Sports', 'medium'),
('strategy', '전략', 'Sports', 'medium'),
('defense', '수비', 'Sports', 'medium'),
('offense', '공격', 'Sports', 'medium'),
('penalty', '페널티', 'Sports', 'medium'),
('overtime', '연장전', 'Sports', 'medium'),
('knockout', '녹아웃', 'Sports', 'medium'),
('endurance', '지구력', 'Sports', 'medium'),
('agility', '민첩성', 'Sports', 'medium'),
('stamina', '체력', 'Sports', 'medium'),
('coordination', '협응력', 'Sports', 'medium'),
('technique', '기술', 'Sports', 'medium'),
('performance', '성적', 'Sports', 'medium'),
('record', '기록', 'Sports', 'medium'),
('victory', '승리', 'Sports', 'medium'),
('defeat', '패배', 'Sports', 'medium'),
('qualifier', '예선', 'Sports', 'medium'),

('decathlon', '10종경기', 'Sports', 'hard'),
('triathlon', '철인3종경기', 'Sports', 'hard'),
('pentathlon', '5종경기', 'Sports', 'hard'),
('biomechanics', '생체역학', 'Sports', 'hard'),
('periodization', '주기화', 'Sports', 'hard'),
('plyometrics', '플라이오메트릭', 'Sports', 'hard'),
('anaerobic', '무산소의', 'Sports', 'hard'),
('aerobic', '유산소의', 'Sports', 'hard'),
('proprioception', '고유수용감각', 'Sports', 'hard'),
('kinesthesia', '운동감각', 'Sports', 'hard'),
('periodization', '주기화훈련', 'Sports', 'hard'),
('tapering', '테이퍼링', 'Sports', 'hard'),
('acclimatization', '순응', 'Sports', 'hard'),
('ergogenic', '운동능력향상의', 'Sports', 'hard'),
('lactate threshold', '젖산역치', 'Sports', 'hard');

-- Technology (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('computer', '컴퓨터', 'Technology', 'easy'),
('phone', '전화', 'Technology', 'easy'),
('internet', '인터넷', 'Technology', 'easy'),
('website', '웹사이트', 'Technology', 'easy'),
('email', '이메일', 'Technology', 'easy'),
('password', '비밀번호', 'Technology', 'easy'),
('keyboard', '키보드', 'Technology', 'easy'),
('mouse', '마우스', 'Technology', 'easy'),
('screen', '화면', 'Technology', 'easy'),
('camera', '카메라', 'Technology', 'easy'),
('video', '비디오', 'Technology', 'easy'),
('photo', '사진', 'Technology', 'easy'),
('app', '앱', 'Technology', 'easy'),
('download', '다운로드', 'Technology', 'easy'),
('upload', '업로드', 'Technology', 'easy'),
('wifi', '와이파이', 'Technology', 'easy'),
('battery', '배터리', 'Technology', 'easy'),
('charger', '충전기', 'Technology', 'easy'),
('printer', '프린터', 'Technology', 'easy'),
('software', '소프트웨어', 'Technology', 'easy'),

('algorithm', '알고리즘', 'Technology', 'medium'),
('database', '데이터베이스', 'Technology', 'medium'),
('server', '서버', 'Technology', 'medium'),
('network', '네트워크', 'Technology', 'medium'),
('bandwidth', '대역폭', 'Technology', 'medium'),
('encryption', '암호화', 'Technology', 'medium'),
('firewall', '방화벽', 'Technology', 'medium'),
('malware', '악성코드', 'Technology', 'medium'),
('virus', '바이러스', 'Technology', 'medium'),
('backup', '백업', 'Technology', 'medium'),
('cloud', '클라우드', 'Technology', 'medium'),
('interface', '인터페이스', 'Technology', 'medium'),
('protocol', '프로토콜', 'Technology', 'medium'),
('router', '라우터', 'Technology', 'medium'),
('browser', '브라우저', 'Technology', 'medium'),
('plugin', '플러그인', 'Technology', 'medium'),
('cache', '캐시', 'Technology', 'medium'),
('cookie', '쿠키', 'Technology', 'medium'),
('debugging', '디버깅', 'Technology', 'medium'),
('compiler', '컴파일러', 'Technology', 'medium'),
('framework', '프레임워크', 'Technology', 'medium'),
('repository', '저장소', 'Technology', 'medium'),
('deployment', '배포', 'Technology', 'medium'),
('scalability', '확장성', 'Technology', 'medium'),
('latency', '지연시간', 'Technology', 'medium'),

('blockchain', '블록체인', 'Technology', 'hard'),
('cryptocurrency', '암호화폐', 'Technology', 'hard'),
('artificial intelligence', '인공지능', 'Technology', 'hard'),
('machine learning', '기계학습', 'Technology', 'hard'),
('neural network', '신경망', 'Technology', 'hard'),
('quantum computing', '양자컴퓨팅', 'Technology', 'hard'),
('virtualization', '가상화', 'Technology', 'hard'),
('containerization', '컨테이너화', 'Technology', 'hard'),
('microservices', '마이크로서비스', 'Technology', 'hard'),
('distributed system', '분산시스템', 'Technology', 'hard'),
('asynchronous', '비동기의', 'Technology', 'hard'),
('concurrency', '동시성', 'Technology', 'hard'),
('parallelism', '병렬성', 'Technology', 'hard'),
('polymorphism', '다형성', 'Technology', 'hard'),
('encapsulation', '캡슐화', 'Technology', 'hard');

-- Nature (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('tree', '나무', 'Nature', 'easy'),
('flower', '꽃', 'Nature', 'easy'),
('grass', '풀', 'Nature', 'easy'),
('mountain', '산', 'Nature', 'easy'),
('river', '강', 'Nature', 'easy'),
('ocean', '바다', 'Nature', 'easy'),
('lake', '호수', 'Nature', 'easy'),
('forest', '숲', 'Nature', 'easy'),
('sky', '하늘', 'Nature', 'easy'),
('cloud', '구름', 'Nature', 'easy'),
('sun', '태양', 'Nature', 'easy'),
('moon', '달', 'Nature', 'easy'),
('star', '별', 'Nature', 'easy'),
('rain', '비', 'Nature', 'easy'),
('snow', '눈', 'Nature', 'easy'),
('wind', '바람', 'Nature', 'easy'),
('stone', '돌', 'Nature', 'easy'),
('sand', '모래', 'Nature', 'easy'),
('leaf', '잎', 'Nature', 'easy'),
('branch', '가지', 'Nature', 'easy'),

('ecosystem', '생태계', 'Nature', 'medium'),
('biodiversity', '생물다양성', 'Nature', 'medium'),
('habitat', '서식지', 'Nature', 'medium'),
('vegetation', '식생', 'Nature', 'medium'),
('photosynthesis', '광합성', 'Nature', 'medium'),
('pollination', '수분', 'Nature', 'medium'),
('erosion', '침식', 'Nature', 'medium'),
('sediment', '퇴적물', 'Nature', 'medium'),
('mineral', '광물', 'Nature', 'medium'),
('fossil', '화석', 'Nature', 'medium'),
('glacier', '빙하', 'Nature', 'medium'),
('volcano', '화산', 'Nature', 'medium'),
('earthquake', '지진', 'Nature', 'medium'),
('tsunami', '쓰나미', 'Nature', 'medium'),
('hurricane', '허리케인', 'Nature', 'medium'),
('tornado', '토네이도', 'Nature', 'medium'),
('drought', '가뭄', 'Nature', 'medium'),
('flood', '홍수', 'Nature', 'medium'),
('climate', '기후', 'Nature', 'medium'),
('atmosphere', '대기', 'Nature', 'medium'),
('precipitation', '강수', 'Nature', 'medium'),
('humidity', '습도', 'Nature', 'medium'),
('temperature', '온도', 'Nature', 'medium'),
('altitude', '고도', 'Nature', 'medium'),
('latitude', '위도', 'Nature', 'medium'),

('geomorphology', '지형학', 'Nature', 'hard'),
('tectonic plates', '지각판', 'Nature', 'hard'),
('metamorphic', '변성의', 'Nature', 'hard'),
('igneous', '화성의', 'Nature', 'hard'),
('sedimentary', '퇴적의', 'Nature', 'hard'),
('stratosphere', '성층권', 'Nature', 'hard'),
('troposphere', '대류권', 'Nature', 'hard'),
('photosynthetic', '광합성의', 'Nature', 'hard'),
('symbiosis', '공생', 'Nature', 'hard'),
('mutualism', '상리공생', 'Nature', 'hard'),
('parasitism', '기생', 'Nature', 'hard'),
('commensalism', '편리공생', 'Nature', 'hard'),
('succession', '천이', 'Nature', 'hard'),
('eutrophication', '부영양화', 'Nature', 'hard'),
('desertification', '사막화', 'Nature', 'hard');

-- Travel (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('trip', '여행', 'Travel', 'easy'),
('hotel', '호텔', 'Travel', 'easy'),
('airport', '공항', 'Travel', 'easy'),
('plane', '비행기', 'Travel', 'easy'),
('train', '기차', 'Travel', 'easy'),
('bus', '버스', 'Travel', 'easy'),
('taxi', '택시', 'Travel', 'easy'),
('ticket', '표', 'Travel', 'easy'),
('passport', '여권', 'Travel', 'easy'),
('luggage', '짐', 'Travel', 'easy'),
('suitcase', '여행가방', 'Travel', 'easy'),
('map', '지도', 'Travel', 'easy'),
('tourist', '관광객', 'Travel', 'easy'),
('guide', '가이드', 'Travel', 'easy'),
('museum', '박물관', 'Travel', 'easy'),
('beach', '해변', 'Travel', 'easy'),
('restaurant', '식당', 'Travel', 'easy'),
('souvenir', '기념품', 'Travel', 'easy'),
('vacation', '휴가', 'Travel', 'easy'),
('destination', '목적지', 'Travel', 'easy'),

('itinerary', '여행일정', 'Travel', 'medium'),
('reservation', '예약', 'Travel', 'medium'),
('accommodation', '숙박', 'Travel', 'medium'),
('boarding pass', '탑승권', 'Travel', 'medium'),
('customs', '세관', 'Travel', 'medium'),
('immigration', '출입국', 'Travel', 'medium'),
('visa', '비자', 'Travel', 'medium'),
('currency', '통화', 'Travel', 'medium'),
('exchange rate', '환율', 'Travel', 'medium'),
('landmark', '명소', 'Travel', 'medium'),
('excursion', '소풍', 'Travel', 'medium'),
('expedition', '탐험', 'Travel', 'medium'),
('backpacking', '배낭여행', 'Travel', 'medium'),
('cruise', '크루즈', 'Travel', 'medium'),
('resort', '리조트', 'Travel', 'medium'),
('hostel', '호스텔', 'Travel', 'medium'),
('campsite', '캠핑장', 'Travel', 'medium'),
('hiking', '하이킹', 'Travel', 'medium'),
('sightseeing', '관광', 'Travel', 'medium'),
('pilgrimage', '순례', 'Travel', 'medium'),
('jet lag', '시차증', 'Travel', 'medium'),
('layover', '경유', 'Travel', 'medium'),
('connecting flight', '연결편', 'Travel', 'medium'),
('departure', '출발', 'Travel', 'medium'),
('arrival', '도착', 'Travel', 'medium'),

('ecotourism', '생태관광', 'Travel', 'hard'),
('sustainable tourism', '지속가능관광', 'Travel', 'hard'),
('expatriate', '해외거주자', 'Travel', 'hard'),
('nomadic', '유목의', 'Travel', 'hard'),
('cosmopolitan', '국제적인', 'Travel', 'hard'),
('indigenous', '토착의', 'Travel', 'hard'),
('vernacular', '토속의', 'Travel', 'hard'),
('diaspora', '디아스포라', 'Travel', 'hard'),
('repatriation', '본국송환', 'Travel', 'hard'),
('quarantine', '검역', 'Travel', 'hard'),
('inoculation', '예방접종', 'Travel', 'hard'),
('acclimatization', '적응', 'Travel', 'hard'),
('cartography', '지도제작', 'Travel', 'hard'),
('topography', '지형', 'Travel', 'hard'),
('longitude', '경도', 'Travel', 'hard');

-- Hobbies (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('hobby', '취미', 'Hobbies', 'easy'),
('game', '게임', 'Hobbies', 'easy'),
('movie', '영화', 'Hobbies', 'easy'),
('music', '음악', 'Hobbies', 'easy'),
('book', '책', 'Hobbies', 'easy'),
('painting', '그림', 'Hobbies', 'easy'),
('drawing', '그리기', 'Hobbies', 'easy'),
('cooking', '요리', 'Hobbies', 'easy'),
('baking', '베이킹', 'Hobbies', 'easy'),
('gardening', '원예', 'Hobbies', 'easy'),
('fishing', '낚시', 'Hobbies', 'easy'),
('camping', '캠핑', 'Hobbies', 'easy'),
('hiking', '등산', 'Hobbies', 'easy'),
('cycling', '자전거타기', 'Hobbies', 'easy'),
('dancing', '춤', 'Hobbies', 'easy'),
('singing', '노래', 'Hobbies', 'easy'),
('photography', '사진', 'Hobbies', 'easy'),
('collection', '수집', 'Hobbies', 'easy'),
('puzzle', '퍼즐', 'Hobbies', 'easy'),
('chess', '체스', 'Hobbies', 'easy'),

('knitting', '뜨개질', 'Hobbies', 'medium'),
('embroidery', '자수', 'Hobbies', 'medium'),
('quilting', '퀼팅', 'Hobbies', 'medium'),
('pottery', '도예', 'Hobbies', 'medium'),
('sculpture', '조각', 'Hobbies', 'medium'),
('calligraphy', '서예', 'Hobbies', 'medium'),
('origami', '종이접기', 'Hobbies', 'medium'),
('woodworking', '목공', 'Hobbies', 'medium'),
('metalwork', '금속공예', 'Hobbies', 'medium'),
('jewelry making', '보석공예', 'Hobbies', 'medium'),
('scrapbooking', '스크랩북', 'Hobbies', 'medium'),
('genealogy', '가계도연구', 'Hobbies', 'medium'),
('astronomy', '천문학', 'Hobbies', 'medium'),
('birdwatching', '조류관찰', 'Hobbies', 'medium'),
('geocaching', '지오캐싱', 'Hobbies', 'medium'),
('archery', '양궁', 'Hobbies', 'medium'),
('fencing', '펜싱', 'Hobbies', 'medium'),
('martial arts', '무술', 'Hobbies', 'medium'),
('meditation', '명상', 'Hobbies', 'medium'),
('yoga', '요가', 'Hobbies', 'medium'),
('pilates', '필라테스', 'Hobbies', 'medium'),
('volunteering', '자원봉사', 'Hobbies', 'medium'),
('blogging', '블로깅', 'Hobbies', 'medium'),
('vlogging', '브이로깅', 'Hobbies', 'medium'),
('podcasting', '팟캐스팅', 'Hobbies', 'medium'),

('philately', '우표수집', 'Hobbies', 'hard'),
('numismatics', '화폐수집', 'Hobbies', 'hard'),
('horticulture', '원예학', 'Hobbies', 'hard'),
('viticulture', '포도재배', 'Hobbies', 'hard'),
('apiculture', '양봉', 'Hobbies', 'hard'),
('taxidermy', '박제', 'Hobbies', 'hard'),
('lapidary', '보석세공', 'Hobbies', 'hard'),
('cartography', '지도제작', 'Hobbies', 'hard'),
('enology', '포도주학', 'Hobbies', 'hard'),
('gastronomy', '미식학', 'Hobbies', 'hard'),
('sommelier', '소믈리에', 'Hobbies', 'hard'),
('barista', '바리스타', 'Hobbies', 'hard'),
('mixology', '칵테일제조', 'Hobbies', 'hard'),
('floristry', '꽃꽂이', 'Hobbies', 'hard'),
('topiary', '나무조형', 'Hobbies', 'hard');

-- Music (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('song', '노래', 'Music', 'easy'),
('sing', '노래하다', 'Music', 'easy'),
('listen', '듣다', 'Music', 'easy'),
('piano', '피아노', 'Music', 'easy'),
('guitar', '기타', 'Music', 'easy'),
('drum', '드럼', 'Music', 'easy'),
('violin', '바이올린', 'Music', 'easy'),
('flute', '플루트', 'Music', 'easy'),
('trumpet', '트럼펫', 'Music', 'easy'),
('singer', '가수', 'Music', 'easy'),
('band', '밴드', 'Music', 'easy'),
('concert', '콘서트', 'Music', 'easy'),
('melody', '멜로디', 'Music', 'easy'),
('rhythm', '리듬', 'Music', 'easy'),
('beat', '박자', 'Music', 'easy'),
('note', '음표', 'Music', 'easy'),
('loud', '큰소리', 'Music', 'easy'),
('quiet', '조용한', 'Music', 'easy'),
('fast', '빠른', 'Music', 'easy'),
('slow', '느린', 'Music', 'easy'),

('orchestra', '오케스트라', 'Music', 'medium'),
('conductor', '지휘자', 'Music', 'medium'),
('composer', '작곡가', 'Music', 'medium'),
('symphony', '교향곡', 'Music', 'medium'),
('harmony', '화음', 'Music', 'medium'),
('chord', '화음', 'Music', 'medium'),
('scale', '음계', 'Music', 'medium'),
('octave', '옥타브', 'Music', 'medium'),
('pitch', '음높이', 'Music', 'medium'),
('tempo', '템포', 'Music', 'medium'),
('dynamics', '셈여림', 'Music', 'medium'),
('timbre', '음색', 'Music', 'medium'),
('genre', '장르', 'Music', 'medium'),
('classical', '클래식', 'Music', 'medium'),
('jazz', '재즈', 'Music', 'medium'),
('rock', '록', 'Music', 'medium'),
('pop', '팝', 'Music', 'medium'),
('blues', '블루스', 'Music', 'medium'),
('folk', '민속음악', 'Music', 'medium'),
('opera', '오페라', 'Music', 'medium'),
('aria', '아리아', 'Music', 'medium'),
('ensemble', '앙상블', 'Music', 'medium'),
('rehearsal', '리허설', 'Music', 'medium'),
('performance', '공연', 'Music', 'medium'),
('improvisation', '즉흥연주', 'Music', 'medium'),

('counterpoint', '대위법', 'Music', 'hard'),
('polyphony', '다성음악', 'Music', 'hard'),
('monophony', '단성음악', 'Music', 'hard'),
('homophony', '화성음악', 'Music', 'hard'),
('cadence', '종지', 'Music', 'hard'),
('modulation', '전조', 'Music', 'hard'),
('chromaticism', '반음계주의', 'Music', 'hard'),
('atonality', '무조성', 'Music', 'hard'),
('serialism', '음렬주의', 'Music', 'hard'),
('fugue', '푸가', 'Music', 'hard'),
('sonata', '소나타', 'Music', 'hard'),
('concerto', '협주곡', 'Music', 'hard'),
('oratorio', '오라토리오', 'Music', 'hard'),
('cantata', '칸타타', 'Music', 'hard'),
('libretto', '대본', 'Music', 'hard');

-- Art (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('art', '예술', 'Art', 'easy'),
('paint', '그리다', 'Art', 'easy'),
('draw', '그리다', 'Art', 'easy'),
('color', '색', 'Art', 'easy'),
('brush', '붓', 'Art', 'easy'),
('canvas', '캔버스', 'Art', 'easy'),
('picture', '그림', 'Art', 'easy'),
('artist', '예술가', 'Art', 'easy'),
('gallery', '갤러리', 'Art', 'easy'),
('museum', '박물관', 'Art', 'easy'),
('statue', '조각상', 'Art', 'easy'),
('portrait', '초상화', 'Art', 'easy'),
('landscape', '풍경화', 'Art', 'easy'),
('sketch', '스케치', 'Art', 'easy'),
('design', '디자인', 'Art', 'easy'),
('pattern', '패턴', 'Art', 'easy'),
('shape', '모양', 'Art', 'easy'),
('line', '선', 'Art', 'easy'),
('texture', '질감', 'Art', 'easy'),
('style', '스타일', 'Art', 'easy'),

('masterpiece', '걸작', 'Art', 'medium'),
('exhibition', '전시회', 'Art', 'medium'),
('sculpture', '조각', 'Art', 'medium'),
('installation', '설치미술', 'Art', 'medium'),
('abstract', '추상적인', 'Art', 'medium'),
('realistic', '사실적인', 'Art', 'medium'),
('impressionism', '인상주의', 'Art', 'medium'),
('expressionism', '표현주의', 'Art', 'medium'),
('cubism', '입체주의', 'Art', 'medium'),
('surrealism', '초현실주의', 'Art', 'medium'),
('renaissance', '르네상스', 'Art', 'medium'),
('baroque', '바로크', 'Art', 'medium'),
('contemporary', '현대의', 'Art', 'medium'),
('perspective', '원근법', 'Art', 'medium'),
('composition', '구도', 'Art', 'medium'),
('proportion', '비율', 'Art', 'medium'),
('symmetry', '대칭', 'Art', 'medium'),
('contrast', '대비', 'Art', 'medium'),
('palette', '팔레트', 'Art', 'medium'),
('pigment', '안료', 'Art', 'medium'),
('watercolor', '수채화', 'Art', 'medium'),
('oil painting', '유화', 'Art', 'medium'),
('acrylic', '아크릴', 'Art', 'medium'),
('fresco', '프레스코', 'Art', 'medium'),
('mural', '벽화', 'Art', 'medium'),

('chiaroscuro', '명암법', 'Art', 'hard'),
('sfumato', '스푸마토', 'Art', 'hard'),
('trompe-loeil', '트롱프뢰유', 'Art', 'hard'),
('impasto', '임파스토', 'Art', 'hard'),
('pointillism', '점묘법', 'Art', 'hard'),
('fauvism', '야수파', 'Art', 'hard'),
('dadaism', '다다이즘', 'Art', 'hard'),
('minimalism', '미니멀리즘', 'Art', 'hard'),
('postmodernism', '포스트모더니즘', 'Art', 'hard'),
('avant-garde', '아방가르드', 'Art', 'hard'),
('provenance', '출처', 'Art', 'hard'),
('patina', '녹청', 'Art', 'hard'),
('gesso', '석고', 'Art', 'hard'),
('encaustic', '밀랍화', 'Art', 'hard'),
('lithography', '석판화', 'Art', 'hard');

-- Science (60개 - easy 20, medium 25, hard 15)
INSERT INTO english_words (word, korean, category, difficulty) VALUES
('science', '과학', 'Science', 'easy'),
('experiment', '실험', 'Science', 'easy'),
('test', '시험', 'Science', 'easy'),
('lab', '실험실', 'Science', 'easy'),
('scientist', '과학자', 'Science', 'easy'),
('chemistry', '화학', 'Science', 'easy'),
('physics', '물리학', 'Science', 'easy'),
('biology', '생물학', 'Science', 'easy'),
('atom', '원자', 'Science', 'easy'),
('molecule', '분자', 'Science', 'easy'),
('cell', '세포', 'Science', 'easy'),
('energy', '에너지', 'Science', 'easy'),
('force', '힘', 'Science', 'easy'),
('gravity', '중력', 'Science', 'easy'),
('light', '빛', 'Science', 'easy'),
('sound', '소리', 'Science', 'easy'),
('heat', '열', 'Science', 'easy'),
('water', '물', 'Science', 'easy'),
('air', '공기', 'Science', 'easy'),
('oxygen', '산소', 'Science', 'easy'),

('hypothesis', '가설', 'Science', 'medium'),
('theory', '이론', 'Science', 'medium'),
('observation', '관찰', 'Science', 'medium'),
('analysis', '분석', 'Science', 'medium'),
('conclusion', '결론', 'Science', 'medium'),
('variable', '변수', 'Science', 'medium'),
('control', '대조군', 'Science', 'medium'),
('data', '데이터', 'Science', 'medium'),
('measurement', '측정', 'Science', 'medium'),
('microscope', '현미경', 'Science', 'medium'),
('telescope', '망원경', 'Science', 'medium'),
('catalyst', '촉매', 'Science', 'medium'),
('reaction', '반응', 'Science', 'medium'),
('compound', '화합물', 'Science', 'medium'),
('element', '원소', 'Science', 'medium'),
('periodic table', '주기율표', 'Science', 'medium'),
('organism', '유기체', 'Science', 'medium'),
('species', '종', 'Science', 'medium'),
('evolution', '진화', 'Science', 'medium'),
('genetics', '유전학', 'Science', 'medium'),
('chromosome', '염색체', 'Science', 'medium'),
('DNA', 'DNA', 'Science', 'medium'),
('protein', '단백질', 'Science', 'medium'),
('enzyme', '효소', 'Science', 'medium'),
('bacteria', '박테리아', 'Science', 'medium'),

('quantum mechanics', '양자역학', 'Science', 'hard'),
('relativity', '상대성이론', 'Science', 'hard'),
('thermodynamics', '열역학', 'Science', 'hard'),
('electromagnetism', '전자기학', 'Science', 'hard'),
('spectroscopy', '분광학', 'Science', 'hard'),
('chromatography', '크로마토그래피', 'Science', 'hard'),
('stoichiometry', '화학양론', 'Science', 'hard'),
('biochemistry', '생화학', 'Science', 'hard'),
('molecular biology', '분자생물학', 'Science', 'hard'),
('cytology', '세포학', 'Science', 'hard'),
('phylogenetics', '계통발생학', 'Science', 'hard'),
('taxonomy', '분류학', 'Science', 'hard'),
('morphology', '형태학', 'Science', 'hard'),
('physiology', '생리학', 'Science', 'hard'),
('homeostasis', '항상성', 'Science', 'hard');
