#!/bin/bash

# 영어 단어 데이터 삽입 (초등학생 수준 100개)
echo "Inserting English words..."

# 동물 (Animals) - Level 1
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''cat'\'', '\''고양이'\'', 1, '\''동물'\'', '\''I have a cat.'\''), ('\''dog'\'', '\''개'\'', 1, '\''동물'\'', '\''The dog is cute.'\''), ('\''bird'\'', '\''새'\'', 1, '\''동물'\'', '\''The bird can fly.'\''), ('\''fish'\'', '\''물고기'\'', 1, '\''동물'\'', '\''Fish live in water.'\''), ('\''rabbit'\'', '\''토끼'\'', 1, '\''동물'\'', '\''The rabbit is white.'\''), ('\''lion'\'', '\''사자'\'', 1, '\''동물'\'', '\''The lion is strong.'\''), ('\''tiger'\'', '\''호랑이'\'', 1, '\''동물'\'', '\''Tigers are big cats.'\''), ('\''elephant'\'', '\''코끼리'\'', 1, '\''동물'\'', '\''Elephants are very big.'\''), ('\''monkey'\'', '\''원숭이'\'', 1, '\''동물'\'', '\''Monkeys like bananas.'\''), ('\''bear'\'', '\''곰'\'', 1, '\''동물'\'', '\''Bears sleep in winter.'\'') ON CONFLICT DO NOTHING;"}'

# 색깔 (Colors) - Level 1
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''red'\'', '\''빨간색'\'', 1, '\''색깔'\'', '\''The apple is red.'\''), ('\''blue'\'', '\''파란색'\'', 1, '\''색깔'\'', '\''The sky is blue.'\''), ('\''yellow'\'', '\''노란색'\'', 1, '\''색깔'\'', '\''The sun is yellow.'\''), ('\''green'\'', '\''초록색'\'', 1, '\''색깔'\'', '\''Grass is green.'\''), ('\''black'\'', '\''검은색'\'', 1, '\''색깔'\'', '\''The night is black.'\''), ('\''white'\'', '\''흰색'\'', 1, '\''색깔'\'', '\''Snow is white.'\''), ('\''orange'\'', '\''주황색'\'', 1, '\''색깔'\'', '\''Oranges are orange.'\''), ('\''purple'\'', '\''보라색'\'', 1, '\''색깔'\'', '\''Grapes are purple.'\''), ('\''pink'\'', '\''분홍색'\'', 1, '\''색깔'\'', '\''The flower is pink.'\''), ('\''brown'\'', '\''갈색'\'', 1, '\''색깔'\'', '\''The bear is brown.'\'') ON CONFLICT DO NOTHING;"}'

# 음식 (Food) - Level 1
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''apple'\'', '\''사과'\'', 1, '\''음식'\'', '\''I eat an apple.'\''), ('\''banana'\'', '\''바나나'\'', 1, '\''음식'\'', '\''Bananas are yellow.'\''), ('\''bread'\'', '\''빵'\'', 1, '\''음식'\'', '\''I like bread.'\''), ('\''milk'\'', '\''우유'\'', 1, '\''음식'\'', '\''Milk is white.'\''), ('\''water'\'', '\''물'\'', 1, '\''음식'\'', '\''I drink water.'\''), ('\''rice'\'', '\''쌀, 밥'\'', 1, '\''음식'\'', '\''We eat rice.'\''), ('\''egg'\'', '\''계란'\'', 1, '\''음식'\'', '\''I have an egg.'\''), ('\''cake'\'', '\''케이크'\'', 1, '\''음식'\'', '\''The cake is sweet.'\''), ('\''pizza'\'', '\''피자'\'', 1, '\''음식'\'', '\''Pizza is delicious.'\''), ('\''chicken'\'', '\''닭고기'\'', 1, '\''음식'\'', '\''I like chicken.'\'') ON CONFLICT DO NOTHING;"}'

# 가족 (Family) - Level 1
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''mother'\'', '\''어머니'\'', 1, '\''가족'\'', '\''My mother is kind.'\''), ('\''father'\'', '\''아버지'\'', 1, '\''가족'\'', '\''My father is tall.'\''), ('\''sister'\'', '\''여자 형제'\'', 1, '\''가족'\'', '\''I have a sister.'\''), ('\''brother'\'', '\''남자 형제'\'', 1, '\''가족'\'', '\''My brother is funny.'\''), ('\''baby'\'', '\''아기'\'', 1, '\''가족'\'', '\''The baby is cute.'\''), ('\''grandmother'\'', '\''할머니'\'', 1, '\''가족'\'', '\''My grandmother is old.'\''), ('\''grandfather'\'', '\''할아버지'\'', 1, '\''가족'\'', '\''My grandfather is wise.'\''), ('\''family'\'', '\''가족'\'', 1, '\''가족'\'', '\''I love my family.'\''), ('\''mom'\'', '\''엄마'\'', 1, '\''가족'\'', '\''Mom, I love you.'\''), ('\''dad'\'', '\''아빠'\'', 1, '\''가족'\'', '\''Dad is strong.'\'') ON CONFLICT DO NOTHING;"}'

# 숫자 (Numbers) - Level 1
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''one'\'', '\''하나'\'', 1, '\''숫자'\'', '\''I have one book.'\''), ('\''two'\'', '\''둘'\'', 1, '\''숫자'\'', '\''I have two eyes.'\''), ('\''three'\'', '\''셋'\'', 1, '\''숫자'\'', '\''I see three birds.'\''), ('\''four'\'', '\''넷'\'', 1, '\''숫자'\'', '\''There are four seasons.'\''), ('\''five'\'', '\''다섯'\'', 1, '\''숫자'\'', '\''I have five fingers.'\''), ('\''six'\'', '\''여섯'\'', 1, '\''숫자'\'', '\''Six plus one is seven.'\''), ('\''seven'\'', '\''일곱'\'', 1, '\''숫자'\'', '\''There are seven days.'\''), ('\''eight'\'', '\''여덟'\'', 1, '\''숫자'\'', '\''I sleep eight hours.'\''), ('\''nine'\'', '\''아홉'\'', 1, '\''숫자'\'', '\''Nine is my lucky number.'\''), ('\''ten'\'', '\''열'\'', 1, '\''숫자'\'', '\''I have ten toes.'\'') ON CONFLICT DO NOTHING;"}'

# 신체 (Body) - Level 1
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''head'\'', '\''머리'\'', 1, '\''신체'\'', '\''I have a head.'\''), ('\''eye'\'', '\''눈'\'', 1, '\''신체'\'', '\''I see with my eyes.'\''), ('\''ear'\'', '\''귀'\'', 1, '\''신체'\'', '\''I hear with my ears.'\''), ('\''nose'\'', '\''코'\'', 1, '\''신체'\'', '\''I smell with my nose.'\''), ('\''mouth'\'', '\''입'\'', 1, '\''신체'\'', '\''I eat with my mouth.'\''), ('\''hand'\'', '\''손'\'', 1, '\''신체'\'', '\''I have two hands.'\''), ('\''foot'\'', '\''발'\'', 1, '\''신체'\'', '\''I walk with my feet.'\''), ('\''arm'\'', '\''팔'\'', 1, '\''신체'\'', '\''My arm is long.'\''), ('\''leg'\'', '\''다리'\'', 1, '\''신체'\'', '\''I run with my legs.'\''), ('\''finger'\'', '\''손가락'\'', 1, '\''신체'\'', '\''I have ten fingers.'\'') ON CONFLICT DO NOTHING;"}'

# 학교 (School) - Level 2
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''school'\'', '\''학교'\'', 2, '\''학교'\'', '\''I go to school.'\''), ('\''teacher'\'', '\''선생님'\'', 2, '\''학교'\'', '\''My teacher is nice.'\''), ('\''student'\'', '\''학생'\'', 2, '\''학교'\'', '\''I am a student.'\''), ('\''book'\'', '\''책'\'', 2, '\''학교'\'', '\''I read a book.'\''), ('\''pencil'\'', '\''연필'\'', 2, '\''학교'\'', '\''I write with a pencil.'\''), ('\''desk'\'', '\''책상'\'', 2, '\''학교'\'', '\''I sit at my desk.'\''), ('\''chair'\'', '\''의자'\'', 2, '\''학교'\'', '\''The chair is comfortable.'\''), ('\''classroom'\'', '\''교실'\'', 2, '\''학교'\'', '\''We study in the classroom.'\''), ('\''homework'\'', '\''숙제'\'', 2, '\''학교'\'', '\''I do my homework.'\''), ('\''friend'\'', '\''친구'\'', 2, '\''학교'\'', '\''She is my friend.'\'') ON CONFLICT DO NOTHING;"}'

# 날씨 (Weather) - Level 2
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''sun'\'', '\''태양'\'', 2, '\''날씨'\'', '\''The sun is bright.'\''), ('\''rain'\'', '\''비'\'', 2, '\''날씨'\'', '\''It will rain today.'\''), ('\''snow'\'', '\''눈'\'', 2, '\''날씨'\'', '\''I like snow.'\''), ('\''wind'\'', '\''바람'\'', 2, '\''날씨'\'', '\''The wind is strong.'\''), ('\''cloud'\'', '\''구름'\'', 2, '\''날씨'\'', '\''I see a cloud.'\''), ('\''hot'\'', '\''뜨거운'\'', 2, '\''날씨'\'', '\''Summer is hot.'\''), ('\''cold'\'', '\''추운'\'', 2, '\''날씨'\'', '\''Winter is cold.'\''), ('\''warm'\'', '\''따뜻한'\'', 2, '\''날씨'\'', '\''Spring is warm.'\''), ('\''cool'\'', '\''시원한'\'', 2, '\''날씨'\'', '\''Fall is cool.'\''), ('\''weather'\'', '\''날씨'\'', 2, '\''날씨'\'', '\''The weather is nice.'\'') ON CONFLICT DO NOTHING;"}'

# 동사 (Verbs) - Level 2
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''eat'\'', '\''먹다'\'', 2, '\''동사'\'', '\''I eat breakfast.'\''), ('\''drink'\'', '\''마시다'\'', 2, '\''동사'\'', '\''I drink water.'\''), ('\''run'\'', '\''달리다'\'', 2, '\''동사'\'', '\''I can run fast.'\''), ('\''walk'\'', '\''걷다'\'', 2, '\''동사'\'', '\''I walk to school.'\''), ('\''jump'\'', '\''뛰다'\'', 2, '\''동사'\'', '\''I can jump high.'\''), ('\''sleep'\'', '\''자다'\'', 2, '\''동사'\'', '\''I sleep at night.'\''), ('\''play'\'', '\''놀다'\'', 2, '\''동사'\'', '\''I play with friends.'\''), ('\''read'\'', '\''읽다'\'', 2, '\''동사'\'', '\''I read books.'\''), ('\''write'\'', '\''쓰다'\'', 2, '\''동사'\'', '\''I write my name.'\''), ('\''sing'\'', '\''노래하다'\'', 2, '\''동사'\'', '\''I like to sing.'\'') ON CONFLICT DO NOTHING;"}'

# 형용사 (Adjectives) - Level 2
manus-mcp-cli tool call execute_sql --server supabase --input '{"project_id":"vqxuavqpevllzzgkpudp","query":"INSERT INTO english_words (word, korean, level, category, example_sentence) VALUES ('\''big'\'', '\''큰'\'', 2, '\''형용사'\'', '\''The elephant is big.'\''), ('\''small'\'', '\''작은'\'', 2, '\''형용사'\'', '\''The ant is small.'\''), ('\''happy'\'', '\''행복한'\'', 2, '\''형용사'\'', '\''I am happy.'\''), ('\''sad'\'', '\''슬픈'\'', 2, '\''형용사'\'', '\''She is sad.'\''), ('\''good'\'', '\''좋은'\'', 2, '\''형용사'\'', '\''This is good.'\''), ('\''bad'\'', '\''나쁜'\'', 2, '\''형용사'\'', '\''That is bad.'\''), ('\''new'\'', '\''새로운'\'', 2, '\''형용사'\'', '\''I have a new toy.'\''), ('\''old'\'', '\''오래된'\'', 2, '\''형용사'\'', '\''This book is old.'\''), ('\''fast'\'', '\''빠른'\'', 2, '\''형용사'\'', '\''The car is fast.'\''), ('\''slow'\'', '\''느린'\'', 2, '\''형용사'\'', '\''The turtle is slow.'\'') ON CONFLICT DO NOTHING;"}'

echo "English words inserted successfully!"
echo "Total: 100 words across 10 categories"
